name: Bat-Tech CI

on: [push, pull_request]  # Runs on push and PR events

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]  # Tests multiple Python versions

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
    
    - name: Run tests
      run: |
        pytest -v --cov=./ --cov-report=xml  # Optional: Add coverage
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      if: always()  # Optional: Uploads coverage to Codecov
